name: test
on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  indexer:
    runs-on: self-hosted
    if: github.repository == 'ClownpieceStripedAbyss/aya-dance-video-index'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jitterbit/get-changed-files@v1
        id: get-changed
        with:
          format: json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Printing changed files
        run: |
          echo "All:"
          echo "${{ steps.get-changed.outputs.all }}"
          echo "Added:"
          echo "${{ steps.get-changed.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.get-changed.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.get-changed.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.get-changed.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.get-changed.outputs.added_modified }}"
      
      - name: Get available ID
        id: get-id
        run: |
          echo "Getting available ID."
          ID=$(bash .github/scripts/find-available-id.sh)
          if [[ -z "$ID" ]]; then
            echo "No available ID found."
            exit 1
          fi
          echo "Available ID: $ID"
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Process added files
        id: added
        run: |
          ID=${{ steps.get-id.outputs.id }}
          echo "Let's start with ID: $ID."

          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
          for added_file in ${added_files[@]}; do
            if [[ "$added_file" == videos/*.md ]]; then
              echo "Processing video markdown file with ID $ID: ${added_file}."
              bash .github/scripts/process-md.sh "$ID" "${added_file}"
              ID=$((ID + 1))
            fi
          done

          echo "New ID for next steps: $ID"
          echo "id=$ID" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: video-indexer-${{ steps.get-id.outputs.id }}_${{ steps.added.outputs.id }}
          path: out/
