name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  indexer:
    runs-on: self-hosted
    if: github.repository == 'ClownpieceStripedAbyss/aya-dance-video-index' && false # disable for now
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find available ID
        run: |
          bash .github/scripts/find-available-id.sh

